image: "hseeberger/scala-sbt:graalvm-ce-21.0.0-java11_1.4.7_2.13.4"

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy -Dsbt.coursier.home=sbt-cache/coursier"
  COURSIER_CACHE: sbt-cache/coursier

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "sbt-cache/sbtboot"
    - "sbt-cache/boot"
    - "sbt-cache/ivy/cache"
    - "sbt-cache/coursier"

stages:
  - test

test:
  script:
    - sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
